### ISSUE TITLE
Parse is Now Shutdown

### ISSUE THREAD

**Issue by lekeope** [bmorelli25/Simple_Uber_Clone#1]
Now that Parse.com can no longer serve as my back end which service can i use that can provide the same functionality?

**Comment by samseen** [comment]
@Edge-Developer, below are some other services you can use: 
Back4app - http://www.back4app.com

Firebase - Build Extraordinary Apps - Firebase

Digital Ocean - Simple Cloud Computing, Built for Developers | DigitalOcean

**Comment by lekeope** [comment]
Thanks

**Comment by lekeope** [comment]
@samseen which do you personally use?

**Comment by lekeope** [comment]
and why?

**Comment by samseen** [comment]
@Edge-Developer, I've used only FireBase and Digital Ocean for something very different. The reason is simple, there owners are giant in the industry and you can quickly get started as there are a lot of documentations you can work with.

**Comment by lekeope** [comment]
@samseen Thanks for Replying, am working on app that should involve sharing files, firebase does not allow me to iterate through the download links of the files neither does it present an array of their links. 

Do you know any Backend as a service i can use? 
PS: am not so versitle with these backends

Thanks
